import Head from 'next/head';
import Link from 'next/link';
import { Fragment } from 'react';
import { ROUTES } from '../config/ROUTES';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {Object.entries(ROUTES)
        .filter(([key]) => key !== 'HOME')
        .map(([key, { display, path }]) => (
          <Fragment key={key}>
            <Link href={path}>
              <a>
                <span style={{ textTransform: 'capitalize' }}>{display}</span>
              </a>
            </Link>
            <br />
          </Fragment>
        ))}
    </>
  );
}
