import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Convert File</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Nothing on home page. Try one of the links above.
    </>
  )
}
